#!/bin/sh

export PATH=/bin

# usage: pseudofs <mountpoint> <fstype>
pseudofs() {
	if test -f /proc/filesystems && ! grep -q "^nodev\t${2}$" /proc/filesystems; then
		return 0
	fi
	if mountpoint -q "$1"; then
		return 0
	fi
	mkdir -p "$1"
	mount -nt "$2" "$2" "$1"
}

pseudofs /proc			proc
pseudofs /dev			devtmpfs
pseudofs /dev/pts		devpts
pseudofs /sys			sysfs
pseudofs /sys/kernel/config	configfs
pseudofs /sys/kernel/debug	debugfs
pseudofs /sys/kernel/tracing	tracefs

ln -fns ../proc/self/fd /dev/fd
mkdir -p /dev/shm

getty -l sh -n 115200 console

echo "Restarting /init"
exec /init
