STAGING = $(CURDIR)/staging
SYSHOST = $(CURDIR)/sysroot
SYSROOT = $(CURDIR)/sysroot/$(TARGET)
WORKDIR = $(CURDIR)/$(MODULE)-build

ARCH = $(firstword $(subst -, ,$(TARGET)))
KARCH = $(ARCH)
ifeq ($(ARCH),aarch64)
KARCH = arm64
MACHINE ?= armv8-a -mtune=cortex-a53
endif
ifeq ($(ARCH),riscv32)
KARCH = riscv
MACHINE ?= rv32gc
endif
ifeq ($(ARCH),riscv64)
KARCH = riscv
MACHINE ?= rv64gc
endif
ifeq ($(ARCH),x86_64)
MACHINE ?= core2
endif

export PATH := $(SYSHOST)/bin:$(PATH)

ifeq ($(CONFIG_NOMMU),y)
CC  = $(TARGET)-gcc --sysroot=$(SYSROOT) -fpie -static -pie
CXX = $(TARGET)-g++ --sysroot=$(SYSROOT) -fpie -static -pie
else
CC  = $(TARGET)-gcc --sysroot=$(SYSROOT) -fno-pie -no-pie
CXX = $(TARGET)-g++ --sysroot=$(SYSROOT) -fno-pie -no-pie
endif
CPP = $(CC) -E

COMMON_CFLAGS = \
    -fdata-sections \
    -ffunction-sections \
    -fno-common \
    -fno-exceptions \
    -fno-stack-clash-protection \
    -fno-stack-protector \
    -fno-unwind-tables \
    -fomit-frame-pointer \
    -g0 \
    -march=$(MACHINE) \
    -Os \
    -Wa,--noexecstack \
    -Werror=implicit-function-declaration
COMMON_LDFLAGS = \
    -Wl,--as-needed \
    -Wl,--exclude-libs,libcrypto.a:libssl.a:libz.a \
    -Wl,--gc-sections \
    -Wl,--hash-style=gnu \
    -Wl,--sort-section=alignment \
    -Wl,-z,noexecstack \
    -Wl,-z,now \
    -Wl,-z,relro

COMMON_FETCH_GIT = \
    git clone --bare $($(MODULE)_SOURCE) $($(MODULE)_LOCAL_SOURCE)
COMMON_FETCH_TAR = \
    wget -nv -O $($(MODULE)_LOCAL_SOURCE) $($(MODULE)_SOURCE)
COMMON_UNPACK_GIT = \
    git clone $($(MODULE)_LOCAL_SOURCE) $(WORKDIR) && \
    git -C $(WORKDIR) checkout -q $($(MODULE)_VERSION:git-%=%)
COMMON_UNPACK_TAR = \
    sha256sum -c hashes/$(notdir $($(MODULE)_LOCAL_SOURCE)).sha256 && \
    busybox tar xf $($(MODULE)_LOCAL_SOURCE) && \
    mv $(MODULE)-$($(MODULE)_VERSION) $(WORKDIR)
COMMON_PREPARE = \
    for f in $$(find -name config.sub); do cp ../tools/config.sub $$f; done; \
    for p in ../patches/$(MODULE)*; do if test -f "$$p"; then patch -p1 -i "$$p"; fi; done
COMMON_CONFIGURE = \
    ./configure CC="$(CC)" CPP="$(CPP)" CXX="$(CXX)" \
    CFLAGS="$(COMMON_CFLAGS) $($(MODULE)_CFLAGS)" LDFLAGS="$(COMMON_LDFLAGS) $($(MODULE)_LDFLAGS)" \
    CONFIG_SITE=../tools/config.site PKG_CONFIG=false \
    --host=$(TARGET) \
    --prefix= --bindir=/bin --libdir=/lib --sbindir=/bin \
    --disable-nls --disable-rpath --enable-static --enable-shared \
    --with-pic
COMMON_COMPILE = \
    $(MAKE) CROSS_COMPILE="$(TARGET)-" CC="$(CC)" CPP="$(CPP)" CXX="$(CXX)" \
    CFLAGS="$(COMMON_CFLAGS) $($(MODULE)_CFLAGS)" LDFLAGS="$(COMMON_LDFLAGS) $($(MODULE)_LDFLAGS)"
COMMON_INSTALL = \
    $(COMMON_COMPILE) DESTDIR="$(SYSROOT)" PREFIX= prefix= install

busybox_VERSION = 1.36.1
busybox_SOURCE = http://busybox.net/downloads/busybox-$(busybox_VERSION).tar.bz2
busybox_DOTCONFIG = tools/busybox$(if $(filter y,$(CONFIG_NOMMU)),-nommu).config
busybox_CONFIGURE = \
    cp ../$(busybox_DOTCONFIG) .config
busybox_INSTALL = \
    install -m0755 busybox -Dt $(SYSROOT)/bin
busybox_BINS = busybox
$(CURDIR)/busybox-build/.configured: $(busybox_DOTCONFIG)

coreboot_VERSION = git-4.22.01
coreboot_SOURCE = https://review.coreboot.org/coreboot
coreboot_CFLAGS = \
    -DCMOS_HAL=1 \
    -I.
coreboot_CONFIGURE = \
    true
coreboot_COMPILE = \
    $(COMMON_COMPILE) -C util/cbmem && \
    $(COMMON_COMPILE) -C util/nvramtool
coreboot_INSTALL = \
    $(COMMON_INSTALL) -C util/cbmem && \
    $(COMMON_INSTALL) -C util/nvramtool
coreboot_BINS = nvramtool

eudev_VERSION = 3.2.14
eudev_SOURCE = https://github.com/eudev-project/eudev/releases/download/v$(eudev_VERSION)/eudev-$(eudev_VERSION).tar.gz
eudev_CONFIGURE = \
    $(COMMON_CONFIGURE) \
    --disable-blkid \
    --disable-introspection \
    --disable-kmod \
    --disable-manpages \
    --disable-mtd_probe \
    --disable-selinux
eudev_BINS = udevadm udevd
eudev_LIBS = libudev.so.1

flashrom_VERSION = v1.2
flashrom_SOURCE = https://download.flashrom.org/releases/flashrom-$(flashrom_VERSION).tar.bz2
flashrom_CONFIGURE = \
    true
flashrom_COMPILE = \
    $(COMMON_COMPILE) CONFIG_INTERNAL=yes CONFIG_NOTHING=yes
flashrom_INSTALL = \
    install -m0755 flashrom -Dt $(SYSROOT)/bin
flashrom_BINS = flashrom

kexec-tools_VERSION = 2.0.27
kexec-tools_SOURCE = https://www.kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-$(kexec-tools_VERSION).tar.xz
kexec-tools_CONFIGURE = \
    $(COMMON_CONFIGURE) \
    --without-lzma \
    --without-xen \
    --without-zlib
kexec-tools_COMPILE = \
    $(MAKE)
kexec-tools_BINS = kexec

libaio_VERSION = 0.3.113
libaio_SOURCE = http://ftp.debian.org/debian/pool/main/liba/libaio/libaio_$(libaio_VERSION).orig.tar.gz
libaio_CFLAGS = \
    -fPIC \
    -I.
libaio_CONFIGURE = \
    true

libtirpc_VERSION = git-libtirpc-1-3-4
libtirpc_SOURCE = git://linux-nfs.org/~steved/libtirpc
libtirpc_PREPARE = \
    $(COMMON_PREPARE) && \
    mkdir tirpc/sys && \
    cp ../tools/queue.h tirpc/sys && \
    ./bootstrap
libtirpc_CONFIGURE = \
    $(COMMON_CONFIGURE) \
    --disable-authdes \
    --disable-gssapi \
    --disable-ipv6 \
    --disable-shared \
    --disable-symvers

linux_VERSION = 6.6.5
linux_SOURCE = https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$(linux_VERSION).tar.xz
linux_CONFIGURE = \
    $(MAKE) ARCH=$(KARCH) CROSS_COMPILE=$(TARGET)- defconfig
linux_COMPILE = \
    cc -o usr/gen_init_cpio.host usr/gen_init_cpio.c && \
    $(CC) $(COMMON_CFLAGS) $($(MODULE)_CFLAGS) $(COMMON_LDFLAGS) $($(MODULE)_LDFLAGS) \
        -o usr/gen_init_cpio.target usr/gen_init_cpio.c && \
    sed -i 's@usr/gen_init_cpio \$$timestamp@cat@' usr/gen_initramfs.sh
linux_INSTALL = \
    install -m0755 usr/gen_init_cpio.host $(SYSHOST)/bin/gen_init_cpio && \
    install -m0755 usr/gen_init_cpio.target $(SYSROOT)/bin/gen_init_cpio && \
    install -m0755 usr/gen_initramfs.sh $(SYSHOST)/bin/gen_initramfs
linux_BINS = gen_init_cpio

lvm2_VERSION = 2.03.23
lvm2_SOURCE = https://mirrors.kernel.org/sourceware/lvm2/LVM2.$(lvm2_VERSION).tgz
lvm2_UNPACK = \
    sha256sum -c hashes/$(notdir $($(MODULE)_LOCAL_SOURCE)).sha256 && \
    tar xf $($(MODULE)_LOCAL_SOURCE) && \
    mv LVM2.$($(MODULE)_VERSION) $(WORKDIR)
lvm2_CONFIGURE = \
    $(COMMON_CONFIGURE) \
    --disable-readline \
    --enable-static_link \
    --with-cache=none \
    --with-thin=none \
    --with-vdo=none
lvm2_COMPILE = \
    $(COMMON_COMPILE) lib.device-mapper
lvm2_INSTALL = \
    $(COMMON_INSTALL:install=install_include install_pkgconfig install_static) -C libdm

musl_VERSION = git-v1.2.5
musl_SOURCE = git://git.musl-libc.org/musl
musl_CONFIGURE = \
    $(COMMON_CONFIGURE) \
    --enable-warnings
musl_LIBS = ld-musl-$(ARCH).so.1

ncurses_VERSION = 6.4
ncurses_SOURCE = https://invisible-mirror.net/archives/ncurses/ncurses-$(ncurses_VERSION).tar.gz
ncurses_CFLAGS = \
    -D_GNU_SOURCE
ncurses_CONFIGURE = \
    $(COMMON_CONFIGURE) \
    --disable-database \
    --disable-db-install \
    --disable-gnat-projects \
    --disable-home-terminfo \
    --disable-rpath-hack \
    --disable-termcap \
    --enable-overwrite \
    --enable-pc-files \
    --enable-warnings \
    --enable-widec \
    --with-cxx \
    --with-fallbacks=linux \
    --with-normal \
    --without-ada \
    --without-curses-h \
    --without-cxx-binding \
    --without-develop \
    --without-gpm \
    --without-manpages \
    --without-progs \
    --without-shared \
    --without-termlib

openssl_VERSION = 3.2.0
openssl_SOURCE = https://www.openssl.org/source/openssl-$(openssl_VERSION).tar.gz
openssl_PREPARE = \
    $(COMMON_PREPARE) && \
    sed -i 's/elif defined(__riscv)/elif defined(OPENSSL_CPUID_OBJ) \&\& defined(__riscv)/' $$(grep -rlF 'elif defined(__riscv)')
openssl_CONFIGURE = \
    env CC="$(CC)" CPP="$(CPP)" CXX="$(CXX)" \
    ./Configure --prefix=/ linux-$(ARCH) \
    no-asm no-async no-autoalginit no-autoerrinit no-autoload-config \
    no-capieng no-comp no-ct \
    no-deprecated no-des no-dgram no-dh no-dso no-dtls \
    no-ec no-ec2m no-engine no-err \
    no-filenames \
    no-gost \
    no-hw no-hw-padlock \
    no-nextprotoneg \
    no-ocsp \
    no-pinshared no-psk \
    no-rdrand no-rfc3779 \
    no-shared no-sock no-srp no-srtp no-ssl no-static-engine \
    no-tests no-threads no-tls no-ts \
    no-ui-console \
    no-zlib \
    $(COMMON_CFLAGS) $($(MODULE)_CFLAGS) $(COMMON_LDFLAGS) $($(MODULE)_LDFLAGS)
openssl_INSTALL = \
    $(COMMON_INSTALL)_sw

pciutils_VERSION = 3.10.0
pciutils_SOURCE = https://www.kernel.org/pub/software/utils/pciutils/pciutils-$(pciutils_VERSION).tar.xz
pciutils_CONFIGURE = \
    true
pciutils_COMPILE = \
    $(COMMON_COMPILE) DNS=no HWDB=no IDSDIR=/ LIBKMOD=no SHARED=no ZLIB=no
pciutils_INSTALL = \
    $(COMMON_INSTALL) STRIP= install-lib

petitboot_VERSION = v1.14
petitboot_SOURCE = https://github.com/open-power/petitboot/releases/download/$(petitboot_VERSION)/petitboot-$(petitboot_VERSION).tar.gz
# HOST_PROG_CRYPTSETUP
# HOST_PROG_DMIDECODE
# HOST_PROG_SCSI_RESCAN
# HOST_PROG_SFTP
# HOST_PROG_SHUTDOWN
# HOST_PROG_VGCHANGE
# HOST_PROG_VGSCAN
petitboot_CONFIGURE = \
    $(COMMON_CONFIGURE) \
    --disable-crypt \
    --disable-mtd \
    --disable-platform-auto \
    --disable-static \
    --enable-busybox \
    --enable-hard-lockdown \
    --with-ncursesw \
    --with-signed-boot=openssl \
    --with-tftp=busybox \
    --without-fdt \
    --without-ncurses \
    --without-twin-fbdev \
    --without-twin-x11 \
    VERIFY_DIGEST=sha256 \
    HOST_PROG_CP=/bin/cp \
    HOST_PROG_IP=/bin/ip \
    HOST_PROG_KEXEC=/bin/kexec \
    HOST_PROG_MOUNT=/bin/mount \
    HOST_PROG_PB_EXEC=/bin/pb-exec \
    HOST_PROG_PB_PLUGIN=/bin/pb-plugin \
    HOST_PROG_SH=/bin/sh \
    HOST_PROG_TFTP=/bin/tftp \
    HOST_PROG_UDHCPC=/bin/udhcpc \
    HOST_PROG_UDHCPC6=/bin/udhcpc6 \
    HOST_PROG_UMOUNT=/bin/umount \
    HOST_PROG_WGET=/bin/wget
petitboot_BINS = pb-config pb-discover pb-event pb-exec pb-plugin pb-sos pb-udhcpc petitboot-nc

toybox_VERSION = 0.8.9
toybox_SOURCE = https://landley.net/toybox/downloads/toybox-$(toybox_VERSION).tar.gz
toybox_CONFIGURE = \
    printf '%s\n' CONFIG_SH=y CONFIG_TOYBOX_FORCE_NOMMU=y > .config && \
    $(MAKE) CROSS_COMPILE="$(TARGET)-" silentoldconfig
toybox_COMPILE = \
    $(MAKE) CROSS_COMPILE="$(TARGET)-" \
    CFLAGS="$(filter-out %-gcc,$(CC)) $(COMMON_CFLAGS) $($(MODULE)_CFLAGS)" LDFLAGS="$(filter-out %-gcc,$(CC)) $(COMMON_LDFLAGS) $($(MODULE)_LDFLAGS)" \
    OUTNAME=toybox
toybox_INSTALL = \
    install -m0755 toybox -Dt $(SYSROOT)/bin
toybox_BINS = toybox

util-linux_VERSION = 2.39.3
util-linux_SOURCE = https://www.kernel.org/pub/linux/utils/util-linux/v2.39/util-linux-$(util-linux_VERSION).tar.xz
util-linux_CONFIGURE = \
    $(COMMON_CONFIGURE) \
    --disable-all-programs \
    --disable-assert \
    --disable-bash-completion \
    --without-btrfs \
    --disable-libfdisk \
    --disable-libmount \
    --disable-libsmartcols \
    --disable-widechar \
    --enable-libblkid \
    --enable-libuuid \
    --without-audit \
    --without-cap-ng \
    --without-libz \
    --without-ncurses \
    --without-ncursesw \
    --without-python \
    --without-readline \
    --without-slang \
    --without-smack \
    --without-systemd \
    --without-tinfo \
    --without-udev \
    --without-user \
    --without-utempter \
    --without-util
util-linux_LIBS = libblkid.so.1 libuuid.so.1

zfs_VERSION = 2.2.2
zfs_SOURCE = https://github.com/zfsonlinux/zfs/releases/download/zfs-$(zfs_VERSION)/zfs-$(zfs_VERSION).tar.gz
# Disable x86 assembly
zfs_PREPARE = \
    $(COMMON_PREPARE) && \
    sed -i -e 's/x86_64 | x86 | i686)/dummy)/' -e 's/curl-config/false/g' configure
zfs_CONFIGURE = \
    $(COMMON_CONFIGURE) \
    --disable-systemd \
    --disable-sysvinit \
    --enable-linux-builtin \
    --with-config=user \
    --with-mounthelperdir=/bin \
    --with-tirpc \
    --without-python \
    ac_cv_header_libudev_h=no \
    ac_cv_search_udev_device_get_is_initialized=no
zfs_BINS = zfs zpool
zfs_LIBS = libnvpair.so.3 libuutil.so.3 libzfs.so.4 libzfs_core.so.3

zlib_VERSION = 1.3.1
zlib_SOURCE = https://www.zlib.net/zlib-$(zlib_VERSION).tar.xz
zlib_CFLAGS = \
    -fPIC
zlib_CONFIGURE = \
    CC="$(CC)" CPP="$(CPP)" CXX="$(CXX)" \
    CFLAGS="$(COMMON_CFLAGS) $($(MODULE)_CFLAGS)" LDFLAGS="$(COMMON_LDFLAGS) $($(MODULE)_LDFLAGS)" \
    ./configure \
    --prefix= \
    --const \
    --static

ifneq ($(findstring git,$($(MODULE)_VERSION)),)
$(MODULE)_LOCAL_SOURCE = sources/$(MODULE).git
else
$(MODULE)_LOCAL_SOURCE = sources/$(notdir $($(MODULE)_SOURCE))
endif

ifeq ($($(MODULE)_FETCH),)
ifneq ($(findstring git,$($(MODULE)_VERSION)),)
$(MODULE)_FETCH = $(COMMON_FETCH_GIT)
else
$(MODULE)_FETCH = $(COMMON_FETCH_TAR)
endif
endif
ifeq ($($(MODULE)_UNPACK),)
ifneq ($(findstring git,$($(MODULE)_VERSION)),)
$(MODULE)_UNPACK = $(COMMON_UNPACK_GIT)
else
$(MODULE)_UNPACK = $(COMMON_UNPACK_TAR)
endif
endif
ifeq ($($(MODULE)_PREPARE),)
$(MODULE)_PREPARE = $(COMMON_PREPARE)
endif
ifeq ($($(MODULE)_CONFIGURE),)
$(MODULE)_CONFIGURE = $(COMMON_CONFIGURE)
endif
ifeq ($($(MODULE)_COMPILE),)
$(MODULE)_COMPILE = $(COMMON_COMPILE)
endif
ifeq ($($(MODULE)_INSTALL),)
$(MODULE)_INSTALL = $(COMMON_INSTALL)
endif

ifeq ($(CONFIG_NOMMU),y)
$(MODULE)_LIBS :=
endif

all: $(WORKDIR)/.staged
fetch: $($(MODULE)_LOCAL_SOURCE)
unpack: $(WORKDIR)/.unpacked
prepare: $(WORKDIR)/.prepared
configure: $(WORKDIR)/.configured
compile: $(WORKDIR)/.compiled
install: $(WORKDIR)/.installed
stage: $(WORKDIR)/.staged

$($(MODULE)_LOCAL_SOURCE):
	$($(MODULE)_FETCH)

$(WORKDIR)/.unpacked: $($(MODULE)_LOCAL_SOURCE)
	$($(MODULE)_UNPACK)
	touch $@

$(WORKDIR)/.prepared: $(WORKDIR)/.unpacked
	cd $(WORKDIR) && $($(MODULE)_PREPARE)
	touch $@

$(WORKDIR)/.configured: $(WORKDIR)/.prepared
	cd $(WORKDIR) && $($(MODULE)_CONFIGURE)
	touch $@

$(WORKDIR)/.compiled: $(WORKDIR)/.configured
	+cd $(WORKDIR) && $($(MODULE)_COMPILE)
	touch $@

$(WORKDIR)/.installed: $(WORKDIR)/.compiled
	+cd $(WORKDIR) && $($(MODULE)_INSTALL)
	find $(SYSROOT) -name '*.la' -delete
	touch $@

$(addprefix $(SYSROOT)/bin/,$($(MODULE)_BINS)): $(WORKDIR)/.installed
$(addprefix $(SYSROOT)/lib/,$($(MODULE)_LIBS)): $(WORKDIR)/.installed

$(STAGING)/%: $(SYSROOT)/%
	$(TARGET)-strip -s -o $@ $<

$(WORKDIR)/.staged: $(addprefix $(STAGING)/bin/,$($(MODULE)_BINS))
$(WORKDIR)/.staged: $(addprefix $(STAGING)/lib/,$($(MODULE)_LIBS))
$(WORKDIR)/.staged:
	touch $@
